### ISSUE TITLE
How do I request new releases to be added to Thoth's knowledge base?

### ISSUE THREAD

**Issue by CermakM** [thoth-station/thamos#195]

**Comment by CermakM** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(<story points>) Thamos should provide more information and user actions when no package releases are found [tags]](https://trello.com/c/tTbxN922/679-story-points-thamos-should-provide-more-information-and-user-actions-when-no-package-releases-are-found-tags)

**Comment by fridex** [comment]
New releases are automatically monitored by [package-releases-job](https://github.com/thoth-station/package-releases-job/) which is run periodically in the cluster.

**Comment by fridex** [comment]
... new releases are automatically scheduled based on the packages kept in the knowledge base (packages that Thoth users use). A new package can be added via environment endpoints or by performing a request to the service with an unknown package. In that case, the service marks down the given package is used and will analyze it so that subsequent requests to the service respond to users.
