### ISSUE TITLE
Is there a way Rich could help thamos output look

### ISSUE THREAD

**Issue by saisankargochhayat** [thoth-station/thamos#466]
I was wondering if we could use this to make the output from `thamos` look better for the end-user. 
Table do look great - https://github.com/willmcgugan/rich#tables

Ref - https://github.com/willmcgugan/rich

**Comment by fridex** [comment]
Sure, it looks better than the current solution using texttable. You can try to rewrite the respective function and let's see how the output looks like.

https://github.com/thoth-station/thamos/blob/fc737dfd8faf0fe6234ef3356307b7c47051ff6d/thamos/cli.py#L170

BTW check if rich has detection for dummy terminals that might be good to have (I would be surprised if not). Otherwise, the output can look like from matrix.
